strangerstudios/pmpro-register-helper

- pmpro-register-helper.php
- readme.txt
When getting back from payment, user registration fields are retrived from `$_SESSION` data and saved.
I found that that **multiple choices fields** are processed as they were **file fields** preventing the former from being correctly saved in user metadata.
```php
[multiple-choice-field] => Array
(
[0] => selected-chioce-1
[1] => selected-chioce-2
[2] => selected-chioce-3
)
[file-field] => Array
(
[name] => foo.jpg
[type] => image/jpeg
[tmp_name] => path/to/file.tmp
[error] => 0
[size] => 32121
)
```
In order to fix it I added a condition to the `if` expression which evaluate whether the field is an image. If $_SESSION field array has a the **'name' key** it's processed as a file, otherwise data is saved as it is.
> Fixed bug which prevented multiple select fields from being saved

- pmpro-register-helper.php
Reported in http://www.paidmembershipspro.com/forums/topic/custom-field-register-helper-bug-using-levels/#post-50062
"NO matter what this field would show up for my level 1 registrations which as you can see is not listed in the “levels” array for the field. Only levels (5,6,7,8) should receive this new field."
> Field displays in spite of $field->levels setting

- pmpro-register-helper.php
This is interfering with a number of other plugin's select boxes. Additionally Wordpress already has select2 dashboard styles/functionality.
> Only include register helper's select2.css/js on the frontend

- pmpro-register-helper.php
If the user forgets/omits to include a call to `pmpro_rh_add_checkbox()` while configuring the RH fields, a PHP Warning will get thrown.
> FIX: PHP Warning if no pmprorh_add_checkbox_box()

- classes/class.field.php
When the readonly attribute is set for a <select> field (type => 'select|multiselect'), we attempted to use the 'readonly="readonly"' attribute in the <select></select> tag. This attribute is not supported by the <select> HTML tag. Instead, we should use 'disabled="disabled"'.
> Using unsupported HTML attribute for <select>

- shortcodes/pmpro_signup.php
Because of the location of the $level test to use the level's title, the pmpro_signup shortcode would always use the blog name rather than the level name as the title unless the admin specified the (optional) 'title' attribute.
Moving the $title & $level check to after the attributes have been processed fixes this issue.
> pmpro_signup uses blogname for default title

- classes/class.field.php
The introduction of `json_encode()` in commit #175e239 breaks JavaScript on checkout.php if there is one or more Register Helper fields with dependencies, and those dependencies contain quote characters. `json_encode()` will correctly code strings anyway, so shouldn't need to include single-quotes to wrap the `json_encode()` calls
> BUG: JavaScript error if RH dependency is defined

- classes/class.field.php
BUG FIX: strtotime() expects parameter 1 to be string, array given
Above error was shown when a required field was left blank. Imploded the array to fix the issue.
> BUG FIX: strtotime() fix.

- classes/class.field.php
Prior RH version wouldn’t keep the date selections if a form was
redisplayed (it wasn’t calc’ing the value correctly). Now, it should.
> Calc pre-fill date correctly.

- pmpro-register-helper.php
The use of `intval()` was stripping leading zeros from numeric values. Examples include zip codes or membership number.
> BUG: Leading zeros were being removed from numeric values

- pmpro-register-helper.php
File Upload fields that were required failed to be recognized after 1.3.5 update
Also added $value = $_FILES[$field->name]; where needed. 
Additional edits to $value may be needed if sanitize is defaulted to true on File Uploads.
> BUG FIX: Required File Upload not recognized

- pmpro-register-helper.php
I've been using `pmpro-email-templates` and I disabled the admin email on checkout.
When successfully registering, the page dies because the hooks handling the emails aren't expecting a potential `false` value.
> Fix conflict with pmpro-email-templates when emails are disabled

- classes/class.field.php
Using `empty()` meant any saved RH field value of 0 would cause the select/multiselect/select2 fields to not select the 0 based key entry
> BUG FIX: 0 is a valid value for a select drop-down

- classes/class.field.php
select2 placeholder attribute has no space after closing double quotation mark resulting in no spacing between placeholder and class HTML attributes 
e.g. classplaceholder="Choose one or more."class="input " instead of placeholder="Choose one or more." class="input "
> Add missing space after select2 placeholder

- css/pmprorh_frontend.css
Special field types need special handling to make them display nicely across themes and all the crazy stuff themes do to inputs.
This update duplicates previous register helper css for checkout fields to also apply to frontend member profile edit fields for pmpro v2.3+
> Adjusting field styles for checkout or profile edit page

- classes/class.field.php
- pmpro-register-helper.php
Required fields are now only enforced if they are being shown on the checkout page, meaning that they are not hidden by a `depends` field and are not a part of a checkout box only shown to new users when a user is currently logged in.
Resolves #70
> Require only if shown

- classes/class.field.php
Now using `pmpro_required` on required input fields, which is what is used in core, and `pmpro_checkout-field-required` on divs surrounding required input fields.
> Fixed classes used on required fields.

- classes/class.field.php
- pmpro-register-helper.php
PMPro 2.9 replaces Register Helper and deactivates it on updating. However, some folks may want to reactivate Register Helper for some reason or at least don't want to encounter a fatal error when trying.
This update uses function_exists and class_exists checks to prevent these errors.
> BUG FIX: Fixed fatal error that would occur if PMPro 2.9+ were already loaded when activating.
> Checking if functions and classes already exists to avoid issues if PMPro 2.9 is already loaded.

- pmpro-register-helper.php
When using HTTPS, this error appears in the JS dev console on `wp-admin` pages:
> Mixed Content: The page at 'https://SITE_DOMAIN/wp-admin/plugins.php' was loaded over HTTPS, but requested an insecure stylesheet 'http://SITE_DOMAIN/wp-content/plugins/pmpro-register-helper/css/pmprorh_admin.css?ver=1.7'. This request has been blocked; the content must be served over HTTPS.
This PR fixes that issue.
1. Install this plugin (and PMPro, of course)
2. View any `wp-admin` page, e.g. `plugins.php`.
3. Open the dev console and ensure the Mixed Content message doesn't appear.
> Fixed mixed content errors on admin pages when using HTTPS.
> Fix mixed content errors in wp-admin when using HTTPS.

- classes/class.field.php
We changed these methods to static due to an error message reported by a customer, but after further review, the error appears to have been a site-specific issue.
> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.
> Revert setting methods to static
