pmpro-register-helper.php

Allow user to modify the header for the Register Helper section (default remains as "More Information").

Add pmprorh_section_header filter

---

classes/class.field.php

Fixed typo on line 477 resulting in "Undefined constant" warning.

Undefined constant warning

---

modules/profile.php

Add a handle when calling wp_enqueue_style() for child themes/themes.

Add handle to wp_enqueue_style() for templates

---

pmpro-register-helper.php

BUG: Would include addmember field regardless of setting
BUG: Incorrect use of current_user_can()
ENHANCEMENT: Simplified addmember test during field processing

BUG: pmprorh_pmpro_add_member_fields() required an optional variable

---

classes/class.field.php

Return true if a conditional checkbox is encountered.

---

pmpro-register-helper.php

ENHCANCEMENT: Load script only on checkout page for RH.
Not sure if we need these files elsewhere

ENHCANCEMENT: Load script only on checkout page

---

classes/class.field.php
modules/profile.php
pmpro-register-helper.php
readme.txt

Incorrect use of static functions when attempting to save RH fields

BUG: Incorrect function definition (static vs non-static).

---

classes/class.field.php

Removed redundant span tag causing HTML5 Validation Issues

span tag issue

---

pmpro-register-helper.php

"To restrict signups to specific users or usernames, enter those email usernames below"
->
"To restrict signups to specific users or usernames, enter those usernames below"

Restrict username typo

---

classes/class.field.php
css/pmprorh_frontend.css

Now wrapping `<li>` elements of grouped checkboxes fields to be inside an `<ul>`.

Wrap <li>s

---

pmpro-register-helper.php

Mmpu compatibility

---

pmpro-register-helper.php

Load Register Helper fields to frontend profile edit using the new hooks that will be part of the v2.3 frontend login features in PMPro: `pmpro_personal_options_update` and `pmpro_show_user_profile`

Adding support to load fields to frontend member profile edit

---

pmpro-register-helper.php
readme.txt

Updating the entire readme, description, and tags.

Readme update v1.6

---

pmpro-register-helper.php

* ENHANCEMENT: Hide front-end profile fields from front-end profile editor page.

Hide only_admin from front-end profile editor

---

pmpro-register-helper.php

Removing old *profile_only* check.
Fixes #142

Remove profile_only check

---

classes/class.field.php

* BUG FIX: readonly option with checkbox field not working. Changed to use disabled attribute instead.

Bug Fix: Checkbox readonly attribute is incorrect.

---

classes/class.field.php

* ENHANCEMENT: Add `pmpro-required` class to required fields for checkout.

Enhancement: Add `pmpro-required` class to required fields.

---

pmpro-register-helper.php

* ENHANCEMENT: Make required error message localized for translations. Also added in general WPCS to this section of code.

Make required error message localized.

---

classes/class.field.php

* ENHANCEMENT: Added classes to radio buttons, grouped check boxes and hidden fields.

Add "Class" attributes to fields.

---

pmpro-register-helper.php
readme.txt

Version bump to 1.6

---

classes/class.field.php

checkbox_grouped fields now show/hide dependencies

---

classes/class.field.php
pmpro-register-helper.php

Make sure that linebreaks in text areas are saved.

---

pmpro-register-helper.php

Membership managers can now view admin only fields

---

classes/class.field.php

Fixed issue where the text '0' would fail required check

---

classes/class.field.php
pmpro-register-helper.php

Fixed issue where blank input for select2/grouped cboxes wouldnt be saved

---

classes/class.field.php

BUG FIX: Fixed an issue of saved for preview and full URL's when using a multisite setup. This stores the uploads in the relevant site upload folder.
The URL's only supported single sites (non-Multisite setups).

BUG FIX: Fixed an issue whith uploaded files for Multisites

---

readme.txt

Improved readme with better keywords and description. Added YouTube video embed.

Updating readme for WordPress.org

---

shortcodes/pmpro_signup.php

* ENHANCEMENT: Escaped output of the signup shortcode.

escape register helper shortcode output.
